stages:
- name: Compile
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: mypipeline/easycrm
      registry: 127.0.0.1:34389
timeout: 60
notification: {}
